### ISSUE TITLE
Todo for README file

### ISSUE THREAD

**Issue by ctseng12** [psych-214-fall-2016/project-red#26]
In the Roadmap section

* Add a simpler version of the flowchart from our presentation as the overview
* Add a blurb about what your section does

**Comment by jcbmiller94** [comment]
I updated my func preprocessing section and added a bit to the intro. Please let me know if it's way too much text, I may have rambled a bit

**Comment by ctseng12** [comment]
I think length is fine!

**Comment by ctseng12** [comment]
Hm, Matthew says "I would use the README file to explain how to get the data, configure the environment, install the code, generate the figures." Should we move our explanations to the report instead?

**Comment by mpnagle** [comment]
We decided to put explanations in the report.
