### ISSUE TITLE
note about tests

### ISSUE THREAD

**Issue by zzbalews** [psych-214-fall-2016/project-red#33]
not really an issue, more of a PSA:

Some of my functions save text, png, or nii files. The tests I'm writing create (and then erase) files in the `fmri_utils/tests` directory. The filenames always start with "temp" so they shouldn't conflict with anything we care about, and they won't produce junky files because the tests will clean up after themselves if everything is working correctly. I hope this is ok! Please let me know if I should be doing this differently :)

**Comment by matthew-brett** [comment]
Maybe check out the Python `tempfile` module : https://docs.python.org/3/library/tempfile.html

Also - have a look at https://github.com/psych-214-fall-2016/fmri-designs/blob/master/fmri_designs/tmpdirs.py in the diagnostics evaluation code.  Example of use in the tests for that module : https://github.com/psych-214-fall-2016/fmri-designs/blob/master/fmri_designs/tests/test_tmpdirs.py

**Comment by zzbalews** [comment]
Will do, thank you!
