### ISSUE TITLE
README files for code 

### ISSUE THREAD

**Issue by ctseng12** [psych-214-fall-2016/project-red#35]
Are we making a README file for each code subfolder (i.e., anatomical preprocessing, fct preprocessing, etc.) or a single README file in the code folder for explanations of what we're doing in each section?

**Comment by zzbalews** [comment]
Could we put everything in the report? That might be a good place for
details since they're probably relevant for whatever results we're
discussing. And then the top level README doesn't get bogged down.

**Comment by ctseng12** [comment]
Maybe? I interpreted Matthew's response on piazza to mean that the report should be super simple/bare bones, but it also makes the most sense to me to put it there.

**Comment by mpnagle** [comment]
Matthew says no, readme info goes into the report.
